// My LinkedIn articles (manually maintained)
export const linkedInArticles = [
    {
        title: 'Required Skills As A Software Engineer',
        link: 'https://www.linkedin.com/pulse/required-skills-software-engineer-saviour-eking/?trackingId=kwOyaCs%2FQWu3eC2BDJ%2FUyw%3D%3D',
        pubDate: '2022-10-3',//October 3, 2022
        content: 'Every wannabe Software engineer has had to ask this question "What are the required skills to be a proficient Software Engineer?". I have asked myself, teachers and friends more than enough times, unfortunately, their answers were never convincing enough.',
        categories: ['software engineering', 'programming']
    },
    {
        title: 'What is Software Engineering',
        link: 'https://www.linkedin.com/pulse/what-software-engineering-saviour-eking/?trackingId=kwOyaCs%2FQWu3eC2BDJ%2FUyw%3D%3D',
        pubDate: '2022-10-6',//October 6, 2022
        content: 'You have probably seen that dude(him/her/they) who is usually with his laptop, and seems to be working always, you then approached him and inquired what he does, then he said "I am a Software Engineer", You wandered what that means because you have always admired his charisma and always wanted to be just like him. Well, in this article, we will be discussing software engineering and why you should be one.',
        categories: ['software engineering', 'programming']
    },
    {
        title: 'For Loops Vs While Loops',
        link: 'https://www.linkedin.com/pulse/loops-vs-while-saviour-eking/?trackingId=kwOyaCs%2FQWu3eC2BDJ%2FUyw%3D%3D',
        pubDate: '2022-11-25',//November 25, 2022
        content: 'Loops are among the most basic and powerful of programming concepts. A loop in a computer program is an instruction that repeats until a specified condition is reached. In a loop structure, the loop asks a question. If the answer requires action, it is executed. The same question is asked again and again until no further action is required. Each time the question is asked is called an iteration. ',
        categories: ['software engineering', 'programming']
    },
    {
        title: 'What is Valgrind',
        link: 'https://www.linkedin.com/pulse/what-valgrind-saviour-eking/?trackingId=kwOyaCs%2FQWu3eC2BDJ%2FUyw%3D%3D',
        pubDate: '2022-12-13',//December 13, 2022
        content: "As a software developer working with C or C++, chances are you've heard of Valgrind. This popular tool is used by many developers to detect and debug memory-related errors in their programs.",
        categories: ['alx', 'software engineering', 'computer programming', 'low level learning']
    },
    {
        title: 'Transform Your Terminal: A Step-by-Step Guide to Show Git Branch in Bash Prompt',
        link: 'https://www.linkedin.com/pulse/transform-your-terminal-step-by-step-guide-show-git-branch-eking/?trackingId=kwOyaCs%2FQWu3eC2BDJ%2FUyw%3D%3D',
        pubDate: '2023-02-8',//February 8, 2023
        content: "As a software developer, you likely spend significant time in the terminal. The terminal is indispensable whether you're working with Git, running scripts, or just navigating your file system. But did you know that you can customize your terminal to make your workflow even more efficient?.",
        categories: ['alx', 'software engineering', 'programming', 'CLI', 'bash', 'linux']
    },
];

export const dummyProjects = {
    "total_count": 7,
    "incomplete_results": false,
    "items": [{
        "id": 804406437,
        "node_id": "R_kgDOL_JEpQ",
        "name": "ctsc",
        "full_name": "TheSaviourEking/ctsc",
        "private": false,
        "owner": {
            "login": "TheSaviourEking",
            "id": 106761645,
            "node_id": "U_kgDOBl0NrQ",
            "avatar_url": "https://avatars.githubusercontent.com/u/106761645?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TheSaviourEking",
            "html_url": "https://github.com/TheSaviourEking",
            "followers_url": "https://api.github.com/users/TheSaviourEking/followers",
            "following_url": "https://api.github.com/users/TheSaviourEking/following{/other_user}",
            "gists_url": "https://api.github.com/users/TheSaviourEking/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TheSaviourEking/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TheSaviourEking/subscriptions",
            "organizations_url": "https://api.github.com/users/TheSaviourEking/orgs",
            "repos_url": "https://api.github.com/users/TheSaviourEking/repos",
            "events_url": "https://api.github.com/users/TheSaviourEking/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TheSaviourEking/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/TheSaviourEking/ctsc",
        "description": "Cracking The Style Code (CTSC) is a dynamic non-profit website dedicated to providing valuable resources and tools for those interested in mastering style, jobs and community. The site is designed to offer an engaging user experience with a responsive design and seamless navigation. ",
        "fork": false,
        "url": "https://api.github.com/repos/TheSaviourEking/ctsc",
        "forks_url": "https://api.github.com/repos/TheSaviourEking/ctsc/forks",
        "keys_url": "https://api.github.com/repos/TheSaviourEking/ctsc/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/TheSaviourEking/ctsc/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/TheSaviourEking/ctsc/teams",
        "hooks_url": "https://api.github.com/repos/TheSaviourEking/ctsc/hooks",
        "issue_events_url": "https://api.github.com/repos/TheSaviourEking/ctsc/issues/events{/number}",
        "events_url": "https://api.github.com/repos/TheSaviourEking/ctsc/events",
        "assignees_url": "https://api.github.com/repos/TheSaviourEking/ctsc/assignees{/user}",
        "branches_url": "https://api.github.com/repos/TheSaviourEking/ctsc/branches{/branch}",
        "tags_url": "https://api.github.com/repos/TheSaviourEking/ctsc/tags",
        "blobs_url": "https://api.github.com/repos/TheSaviourEking/ctsc/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/TheSaviourEking/ctsc/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/TheSaviourEking/ctsc/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/TheSaviourEking/ctsc/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/TheSaviourEking/ctsc/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/TheSaviourEking/ctsc/languages",
        "stargazers_url": "https://api.github.com/repos/TheSaviourEking/ctsc/stargazers",
        "contributors_url": "https://api.github.com/repos/TheSaviourEking/ctsc/contributors",
        "subscribers_url": "https://api.github.com/repos/TheSaviourEking/ctsc/subscribers",
        "subscription_url": "https://api.github.com/repos/TheSaviourEking/ctsc/subscription",
        "commits_url": "https://api.github.com/repos/TheSaviourEking/ctsc/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/TheSaviourEking/ctsc/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/TheSaviourEking/ctsc/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/TheSaviourEking/ctsc/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/TheSaviourEking/ctsc/contents/{+path}",
        "compare_url": "https://api.github.com/repos/TheSaviourEking/ctsc/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/TheSaviourEking/ctsc/merges",
        "archive_url": "https://api.github.com/repos/TheSaviourEking/ctsc/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/TheSaviourEking/ctsc/downloads",
        "issues_url": "https://api.github.com/repos/TheSaviourEking/ctsc/issues{/number}",
        "pulls_url": "https://api.github.com/repos/TheSaviourEking/ctsc/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/TheSaviourEking/ctsc/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/TheSaviourEking/ctsc/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/TheSaviourEking/ctsc/labels{/name}",
        "releases_url": "https://api.github.com/repos/TheSaviourEking/ctsc/releases{/id}",
        "deployments_url": "https://api.github.com/repos/TheSaviourEking/ctsc/deployments",
        "created_at": "2024-05-22T14:24:09Z",
        "updated_at": "2024-07-23T22:56:54Z",
        "pushed_at": "2024-07-13T11:38:27Z",
        "git_url": "git://github.com/TheSaviourEking/ctsc.git",
        "ssh_url": "git@github.com:TheSaviourEking/ctsc.git",
        "clone_url": "https://github.com/TheSaviourEking/ctsc.git",
        "svn_url": "https://github.com/TheSaviourEking/ctsc",
        "homepage": "https://stylecodex.netlify.app/",
        "size": 12841,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "portfolio",
            "project"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "permissions": {
            "admin": true,
            "maintain": true,
            "push": true,
            "triage": true,
            "pull": true
        },
        "score": 1
    },
    {
        "id": 658359246,
        "node_id": "R_kgDOJz3Dzg",
        "name": "portfolio-v0.1.0",
        "full_name": "TheSaviourEking/portfolio-v0.1.0",
        "private": false,
        "owner": {
            "login": "TheSaviourEking",
            "id": 106761645,
            "node_id": "U_kgDOBl0NrQ",
            "avatar_url": "https://avatars.githubusercontent.com/u/106761645?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TheSaviourEking",
            "html_url": "https://github.com/TheSaviourEking",
            "followers_url": "https://api.github.com/users/TheSaviourEking/followers",
            "following_url": "https://api.github.com/users/TheSaviourEking/following{/other_user}",
            "gists_url": "https://api.github.com/users/TheSaviourEking/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TheSaviourEking/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TheSaviourEking/subscriptions",
            "organizations_url": "https://api.github.com/users/TheSaviourEking/orgs",
            "repos_url": "https://api.github.com/users/TheSaviourEking/repos",
            "events_url": "https://api.github.com/users/TheSaviourEking/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TheSaviourEking/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/TheSaviourEking/portfolio-v0.1.0",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0",
        "forks_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/forks",
        "keys_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/teams",
        "hooks_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/hooks",
        "issue_events_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/issues/events{/number}",
        "events_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/events",
        "assignees_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/assignees{/user}",
        "branches_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/branches{/branch}",
        "tags_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/tags",
        "blobs_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/languages",
        "stargazers_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/stargazers",
        "contributors_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/contributors",
        "subscribers_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/subscribers",
        "subscription_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/subscription",
        "commits_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/contents/{+path}",
        "compare_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/merges",
        "archive_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/downloads",
        "issues_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/issues{/number}",
        "pulls_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/labels{/name}",
        "releases_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/releases{/id}",
        "deployments_url": "https://api.github.com/repos/TheSaviourEking/portfolio-v0.1.0/deployments",
        "created_at": "2023-06-25T14:17:13Z",
        "updated_at": "2024-07-23T22:19:22Z",
        "pushed_at": "2024-07-23T22:19:23Z",
        "git_url": "git://github.com/TheSaviourEking/portfolio-v0.1.0.git",
        "ssh_url": "git@github.com:TheSaviourEking/portfolio-v0.1.0.git",
        "clone_url": "https://github.com/TheSaviourEking/portfolio-v0.1.0.git",
        "svn_url": "https://github.com/TheSaviourEking/portfolio-v0.1.0",
        "homepage": "https://thesavioureking.github.io/portfolio-v0.1.0/",
        "size": 1381,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "portfolio",
            "portfolio-template",
            "portfolio-website",
            "project"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "permissions": {
            "admin": true,
            "maintain": true,
            "push": true,
            "triage": true,
            "pull": true
        },
        "score": 1
    },
    {
        "id": 649901132,
        "node_id": "R_kgDOJry0TA",
        "name": "EvoCoreOS",
        "full_name": "TheSaviourEking/EvoCoreOS",
        "private": false,
        "owner": {
            "login": "TheSaviourEking",
            "id": 106761645,
            "node_id": "U_kgDOBl0NrQ",
            "avatar_url": "https://avatars.githubusercontent.com/u/106761645?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TheSaviourEking",
            "html_url": "https://github.com/TheSaviourEking",
            "followers_url": "https://api.github.com/users/TheSaviourEking/followers",
            "following_url": "https://api.github.com/users/TheSaviourEking/following{/other_user}",
            "gists_url": "https://api.github.com/users/TheSaviourEking/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TheSaviourEking/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TheSaviourEking/subscriptions",
            "organizations_url": "https://api.github.com/users/TheSaviourEking/orgs",
            "repos_url": "https://api.github.com/users/TheSaviourEking/repos",
            "events_url": "https://api.github.com/users/TheSaviourEking/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TheSaviourEking/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/TheSaviourEking/EvoCoreOS",
        "description": "A simple operating system",
        "fork": false,
        "url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS",
        "forks_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/forks",
        "keys_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/teams",
        "hooks_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/hooks",
        "issue_events_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/issues/events{/number}",
        "events_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/events",
        "assignees_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/assignees{/user}",
        "branches_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/branches{/branch}",
        "tags_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/tags",
        "blobs_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/languages",
        "stargazers_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/stargazers",
        "contributors_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/contributors",
        "subscribers_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/subscribers",
        "subscription_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/subscription",
        "commits_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/contents/{+path}",
        "compare_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/merges",
        "archive_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/downloads",
        "issues_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/issues{/number}",
        "pulls_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/labels{/name}",
        "releases_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/releases{/id}",
        "deployments_url": "https://api.github.com/repos/TheSaviourEking/EvoCoreOS/deployments",
        "created_at": "2023-06-05T22:23:04Z",
        "updated_at": "2024-07-23T06:19:53Z",
        "pushed_at": "2023-06-07T23:03:34Z",
        "git_url": "git://github.com/TheSaviourEking/EvoCoreOS.git",
        "ssh_url": "git@github.com:TheSaviourEking/EvoCoreOS.git",
        "clone_url": "https://github.com/TheSaviourEking/EvoCoreOS.git",
        "svn_url": "https://github.com/TheSaviourEking/EvoCoreOS",
        "homepage": "",
        "size": 22,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Assembly",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": true,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 1,
        "license": {
            "key": "gpl-3.0",
            "name": "GNU General Public License v3.0",
            "spdx_id": "GPL-3.0",
            "url": "https://api.github.com/licenses/gpl-3.0",
            "node_id": "MDc6TGljZW5zZTk="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "c",
            "cli",
            "os",
            "portfolio",
            "project"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "main",
        "permissions": {
            "admin": true,
            "maintain": true,
            "push": true,
            "triage": true,
            "pull": true
        },
        "score": 1
    },
    {
        "id": 831586862,
        "node_id": "R_kgDOMZECLg",
        "name": "portfolio",
        "full_name": "TheSaviourEking/portfolio",
        "private": false,
        "owner": {
            "login": "TheSaviourEking",
            "id": 106761645,
            "node_id": "U_kgDOBl0NrQ",
            "avatar_url": "https://avatars.githubusercontent.com/u/106761645?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TheSaviourEking",
            "html_url": "https://github.com/TheSaviourEking",
            "followers_url": "https://api.github.com/users/TheSaviourEking/followers",
            "following_url": "https://api.github.com/users/TheSaviourEking/following{/other_user}",
            "gists_url": "https://api.github.com/users/TheSaviourEking/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TheSaviourEking/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TheSaviourEking/subscriptions",
            "organizations_url": "https://api.github.com/users/TheSaviourEking/orgs",
            "repos_url": "https://api.github.com/users/TheSaviourEking/repos",
            "events_url": "https://api.github.com/users/TheSaviourEking/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TheSaviourEking/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/TheSaviourEking/portfolio",
        "description": "Welcome to my digital showcase! This personal portfolio website is a testament to my skills in modern web development, built from the ground up using Next.js and React. It leverages the power of server-side rendering and static site generation to deliver a blazing-fast, SEO-friendly experience. ",
        "fork": false,
        "url": "https://api.github.com/repos/TheSaviourEking/portfolio",
        "forks_url": "https://api.github.com/repos/TheSaviourEking/portfolio/forks",
        "keys_url": "https://api.github.com/repos/TheSaviourEking/portfolio/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/TheSaviourEking/portfolio/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/TheSaviourEking/portfolio/teams",
        "hooks_url": "https://api.github.com/repos/TheSaviourEking/portfolio/hooks",
        "issue_events_url": "https://api.github.com/repos/TheSaviourEking/portfolio/issues/events{/number}",
        "events_url": "https://api.github.com/repos/TheSaviourEking/portfolio/events",
        "assignees_url": "https://api.github.com/repos/TheSaviourEking/portfolio/assignees{/user}",
        "branches_url": "https://api.github.com/repos/TheSaviourEking/portfolio/branches{/branch}",
        "tags_url": "https://api.github.com/repos/TheSaviourEking/portfolio/tags",
        "blobs_url": "https://api.github.com/repos/TheSaviourEking/portfolio/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/TheSaviourEking/portfolio/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/TheSaviourEking/portfolio/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/TheSaviourEking/portfolio/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/TheSaviourEking/portfolio/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/TheSaviourEking/portfolio/languages",
        "stargazers_url": "https://api.github.com/repos/TheSaviourEking/portfolio/stargazers",
        "contributors_url": "https://api.github.com/repos/TheSaviourEking/portfolio/contributors",
        "subscribers_url": "https://api.github.com/repos/TheSaviourEking/portfolio/subscribers",
        "subscription_url": "https://api.github.com/repos/TheSaviourEking/portfolio/subscription",
        "commits_url": "https://api.github.com/repos/TheSaviourEking/portfolio/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/TheSaviourEking/portfolio/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/TheSaviourEking/portfolio/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/TheSaviourEking/portfolio/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/TheSaviourEking/portfolio/contents/{+path}",
        "compare_url": "https://api.github.com/repos/TheSaviourEking/portfolio/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/TheSaviourEking/portfolio/merges",
        "archive_url": "https://api.github.com/repos/TheSaviourEking/portfolio/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/TheSaviourEking/portfolio/downloads",
        "issues_url": "https://api.github.com/repos/TheSaviourEking/portfolio/issues{/number}",
        "pulls_url": "https://api.github.com/repos/TheSaviourEking/portfolio/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/TheSaviourEking/portfolio/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/TheSaviourEking/portfolio/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/TheSaviourEking/portfolio/labels{/name}",
        "releases_url": "https://api.github.com/repos/TheSaviourEking/portfolio/releases{/id}",
        "deployments_url": "https://api.github.com/repos/TheSaviourEking/portfolio/deployments",
        "created_at": "2024-07-21T02:34:36Z",
        "updated_at": "2024-07-24T04:55:51Z",
        "pushed_at": "2024-07-24T04:55:51Z",
        "git_url": "git://github.com/TheSaviourEking/portfolio.git",
        "ssh_url": "git@github.com:TheSaviourEking/portfolio.git",
        "clone_url": "https://github.com/TheSaviourEking/portfolio.git",
        "svn_url": "https://github.com/TheSaviourEking/portfolio",
        "homepage": "",
        "size": 5932,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
            "key": "other",
            "name": "Other",
            "spdx_id": "NOASSERTION",
            "url": null,
            "node_id": "MDc6TGljZW5zZTA="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "portfolio",
            "portfolio-website",
            "project"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "permissions": {
            "admin": true,
            "maintain": true,
            "push": true,
            "triage": true,
            "pull": true
        },
        "score": 1
    },
    {
        "id": 827674517,
        "node_id": "R_kgDOMVVPlQ",
        "name": "amce-ledger",
        "full_name": "TheSaviourEking/amce-ledger",
        "private": false,
        "owner": {
            "login": "TheSaviourEking",
            "id": 106761645,
            "node_id": "U_kgDOBl0NrQ",
            "avatar_url": "https://avatars.githubusercontent.com/u/106761645?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TheSaviourEking",
            "html_url": "https://github.com/TheSaviourEking",
            "followers_url": "https://api.github.com/users/TheSaviourEking/followers",
            "following_url": "https://api.github.com/users/TheSaviourEking/following{/other_user}",
            "gists_url": "https://api.github.com/users/TheSaviourEking/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TheSaviourEking/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TheSaviourEking/subscriptions",
            "organizations_url": "https://api.github.com/users/TheSaviourEking/orgs",
            "repos_url": "https://api.github.com/users/TheSaviourEking/repos",
            "events_url": "https://api.github.com/users/TheSaviourEking/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TheSaviourEking/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/TheSaviourEking/amce-ledger",
        "description": "AMCE ledger is a comprehensive dashboard application designed for managing company invoices. Targeted at businesses needing large-scale invoice management with a flexible UI, it consolidates viewing invoices, customers, and dashboard data all in one place.",
        "fork": false,
        "url": "https://api.github.com/repos/TheSaviourEking/amce-ledger",
        "forks_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/forks",
        "keys_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/teams",
        "hooks_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/hooks",
        "issue_events_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/issues/events{/number}",
        "events_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/events",
        "assignees_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/assignees{/user}",
        "branches_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/branches{/branch}",
        "tags_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/tags",
        "blobs_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/languages",
        "stargazers_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/stargazers",
        "contributors_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/contributors",
        "subscribers_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/subscribers",
        "subscription_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/subscription",
        "commits_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/contents/{+path}",
        "compare_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/merges",
        "archive_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/downloads",
        "issues_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/issues{/number}",
        "pulls_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/labels{/name}",
        "releases_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/releases{/id}",
        "deployments_url": "https://api.github.com/repos/TheSaviourEking/amce-ledger/deployments",
        "created_at": "2024-07-12T06:29:57Z",
        "updated_at": "2024-07-23T06:11:53Z",
        "pushed_at": "2024-07-14T17:30:27Z",
        "git_url": "git://github.com/TheSaviourEking/amce-ledger.git",
        "ssh_url": "git@github.com:TheSaviourEking/amce-ledger.git",
        "clone_url": "https://github.com/TheSaviourEking/amce-ledger.git",
        "svn_url": "https://github.com/TheSaviourEking/amce-ledger",
        "homepage": "https://acme-ledger.vercel.app",
        "size": 940,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "TypeScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "portfolio",
            "project"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "permissions": {
            "admin": true,
            "maintain": true,
            "push": true,
            "triage": true,
            "pull": true
        },
        "score": 1
    },
    {
        "id": 825465563,
        "node_id": "R_kgDOMTOa2w",
        "name": "AuthOrg",
        "full_name": "TheSaviourEking/AuthOrg",
        "private": false,
        "owner": {
            "login": "TheSaviourEking",
            "id": 106761645,
            "node_id": "U_kgDOBl0NrQ",
            "avatar_url": "https://avatars.githubusercontent.com/u/106761645?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TheSaviourEking",
            "html_url": "https://github.com/TheSaviourEking",
            "followers_url": "https://api.github.com/users/TheSaviourEking/followers",
            "following_url": "https://api.github.com/users/TheSaviourEking/following{/other_user}",
            "gists_url": "https://api.github.com/users/TheSaviourEking/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TheSaviourEking/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TheSaviourEking/subscriptions",
            "organizations_url": "https://api.github.com/users/TheSaviourEking/orgs",
            "repos_url": "https://api.github.com/users/TheSaviourEking/repos",
            "events_url": "https://api.github.com/users/TheSaviourEking/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TheSaviourEking/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/TheSaviourEking/AuthOrg",
        "description": "AuthOrg is a robust authentication and authorization system designed to manage users and their access to organization-specific data. This project features secure user registration, login, and token-based authentication, ensuring that only authorized users can access specific organizational data.",
        "fork": false,
        "url": "https://api.github.com/repos/TheSaviourEking/AuthOrg",
        "forks_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/forks",
        "keys_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/teams",
        "hooks_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/hooks",
        "issue_events_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/issues/events{/number}",
        "events_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/events",
        "assignees_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/assignees{/user}",
        "branches_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/branches{/branch}",
        "tags_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/tags",
        "blobs_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/languages",
        "stargazers_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/stargazers",
        "contributors_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/contributors",
        "subscribers_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/subscribers",
        "subscription_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/subscription",
        "commits_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/contents/{+path}",
        "compare_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/merges",
        "archive_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/downloads",
        "issues_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/issues{/number}",
        "pulls_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/labels{/name}",
        "releases_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/releases{/id}",
        "deployments_url": "https://api.github.com/repos/TheSaviourEking/AuthOrg/deployments",
        "created_at": "2024-07-07T21:12:20Z",
        "updated_at": "2024-07-23T06:12:42Z",
        "pushed_at": "2024-07-13T03:13:03Z",
        "git_url": "git://github.com/TheSaviourEking/AuthOrg.git",
        "ssh_url": "git@github.com:TheSaviourEking/AuthOrg.git",
        "clone_url": "https://github.com/TheSaviourEking/AuthOrg.git",
        "svn_url": "https://github.com/TheSaviourEking/AuthOrg",
        "homepage": "https://authorg.onrender.com",
        "size": 100,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "portfolio",
            "project"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "permissions": {
            "admin": true,
            "maintain": true,
            "push": true,
            "triage": true,
            "pull": true
        },
        "score": 1
    },
    {
        "id": 795994510,
        "node_id": "R_kgDOL3Hpjg",
        "name": "art-museum",
        "full_name": "TheSaviourEking/art-museum",
        "private": false,
        "owner": {
            "login": "TheSaviourEking",
            "id": 106761645,
            "node_id": "U_kgDOBl0NrQ",
            "avatar_url": "https://avatars.githubusercontent.com/u/106761645?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/TheSaviourEking",
            "html_url": "https://github.com/TheSaviourEking",
            "followers_url": "https://api.github.com/users/TheSaviourEking/followers",
            "following_url": "https://api.github.com/users/TheSaviourEking/following{/other_user}",
            "gists_url": "https://api.github.com/users/TheSaviourEking/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/TheSaviourEking/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/TheSaviourEking/subscriptions",
            "organizations_url": "https://api.github.com/users/TheSaviourEking/orgs",
            "repos_url": "https://api.github.com/users/TheSaviourEking/repos",
            "events_url": "https://api.github.com/users/TheSaviourEking/events{/privacy}",
            "received_events_url": "https://api.github.com/users/TheSaviourEking/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/TheSaviourEking/art-museum",
        "description": "A purely frontend application that displays a list of art galleries. The information about the art galleries will be seeded using data extracted from the Harvard Art Museum API.",
        "fork": false,
        "url": "https://api.github.com/repos/TheSaviourEking/art-museum",
        "forks_url": "https://api.github.com/repos/TheSaviourEking/art-museum/forks",
        "keys_url": "https://api.github.com/repos/TheSaviourEking/art-museum/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/TheSaviourEking/art-museum/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/TheSaviourEking/art-museum/teams",
        "hooks_url": "https://api.github.com/repos/TheSaviourEking/art-museum/hooks",
        "issue_events_url": "https://api.github.com/repos/TheSaviourEking/art-museum/issues/events{/number}",
        "events_url": "https://api.github.com/repos/TheSaviourEking/art-museum/events",
        "assignees_url": "https://api.github.com/repos/TheSaviourEking/art-museum/assignees{/user}",
        "branches_url": "https://api.github.com/repos/TheSaviourEking/art-museum/branches{/branch}",
        "tags_url": "https://api.github.com/repos/TheSaviourEking/art-museum/tags",
        "blobs_url": "https://api.github.com/repos/TheSaviourEking/art-museum/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/TheSaviourEking/art-museum/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/TheSaviourEking/art-museum/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/TheSaviourEking/art-museum/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/TheSaviourEking/art-museum/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/TheSaviourEking/art-museum/languages",
        "stargazers_url": "https://api.github.com/repos/TheSaviourEking/art-museum/stargazers",
        "contributors_url": "https://api.github.com/repos/TheSaviourEking/art-museum/contributors",
        "subscribers_url": "https://api.github.com/repos/TheSaviourEking/art-museum/subscribers",
        "subscription_url": "https://api.github.com/repos/TheSaviourEking/art-museum/subscription",
        "commits_url": "https://api.github.com/repos/TheSaviourEking/art-museum/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/TheSaviourEking/art-museum/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/TheSaviourEking/art-museum/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/TheSaviourEking/art-museum/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/TheSaviourEking/art-museum/contents/{+path}",
        "compare_url": "https://api.github.com/repos/TheSaviourEking/art-museum/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/TheSaviourEking/art-museum/merges",
        "archive_url": "https://api.github.com/repos/TheSaviourEking/art-museum/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/TheSaviourEking/art-museum/downloads",
        "issues_url": "https://api.github.com/repos/TheSaviourEking/art-museum/issues{/number}",
        "pulls_url": "https://api.github.com/repos/TheSaviourEking/art-museum/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/TheSaviourEking/art-museum/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/TheSaviourEking/art-museum/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/TheSaviourEking/art-museum/labels{/name}",
        "releases_url": "https://api.github.com/repos/TheSaviourEking/art-museum/releases{/id}",
        "deployments_url": "https://api.github.com/repos/TheSaviourEking/art-museum/deployments",
        "created_at": "2024-05-04T16:09:08Z",
        "updated_at": "2024-07-23T22:13:18Z",
        "pushed_at": "2024-05-08T04:36:29Z",
        "git_url": "git://github.com/TheSaviourEking/art-museum.git",
        "ssh_url": "git@github.com:TheSaviourEking/art-museum.git",
        "clone_url": "https://github.com/TheSaviourEking/art-museum.git",
        "svn_url": "https://github.com/TheSaviourEking/art-museum",
        "homepage": "",
        "size": 316,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "portfolio",
            "project"
        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "permissions": {
            "admin": true,
            "maintain": true,
            "push": true,
            "triage": true,
            "pull": true
        },
        "score": 1
    }
    ]
}
