import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Navigation";
import Footer from "./components/Footer.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className={`${inter.className} p-4 container mx-auto flex flex-col min-h-screen`}>
        <NavBar />
        <main className="mt-20 md:mt-10 text-text container flex-grow px-4 md:px-0">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
