import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Navigation";
import Footer from "./components/Footer.jsx";

import StoreProvider from "./StoreProvider";
import { makeStore } from "@/store";
import { fetchProjects } from "@/store/projects/projectsSlice";
import InitialDataFetcher from "./components/InitialDataFetcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const store = makeStore();
  // await store.dispatch(fetchProjects());
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <StoreProvider>
        <InitialDataFetcher>
          <body className={`${inter.className} p-4 container mx-auto flex flex-col min-h-screen`}>
            <NavBar />
            <main className="mt-20 md:mt-10 text-text container flex-grow px-4 md:px-0">
              {/* {children} */}
              {children}
            </main>
            <Footer />
          </body>
        </InitialDataFetcher>
      </StoreProvider>
    </html>
  );
}
