import type { Metadata } from "next";
import localFont from "next/font/local";
import { GFS_Neohellenic } from 'next/font/google';

import "./globals.css";

import Navbar from "@/sections/Navbar";
import Footer from "@/sections/Footer";

const gfsNeohellenic = GFS_Neohellenic(
  {
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    display: 'swap',
    subsets: ['greek'],
    variable: '--font-neohellenic'
  }
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const response = await fetch('https://api.github.com/users/YOUR_USERNAME/repos', {
    headers: {
      Authorization: `token ${process.env.GITHUB_TOKEN}`,
    },
    next: { revalidate: 60 }, // ISR
  });

  const projects = await response.json();

  return (
    <html lang="en">
      <body
        className={`${gfsNeohellenic.variable} antialiased`}
      >
        <Navbar />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
