import type { Metadata } from "next";
import localFont from "next/font/local";
import {GFS_Neohellenic} from 'next/font/google';

import "./globals.css";

import Navbar from "@/sections/Navbar";
import Footer from "@/sections/Footer";

const geistSans = localFont({
  src: "../../public//fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const gfsNeohellenic = GFS_Neohellenic(
 {
   weight: ['400', '700'],
   style:['normal','italic'],
   display:'swap',
   subsets:['greek'],
   variable:'--font-neohellenic'
 }
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${gfsNeohellenic.variable} antialiased`}
      >
        <Navbar />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
